export const errorCodes = {
	NO_RESOURCE: 1001,
	VALIDATION_ERROR_BAD_DURATION: 1401,
  VALIDATION_ERROR_UNKNOWN: 1499,
	UNKNOWN_ERROR: 9999,
};

export const successCodes = {
	SUBMIT_BOOKING_SUCCESS: 2001,
};